Algoritmo "pares_consecutivos"

Var

   x, soma : inteiro

Inicio

      x <- 0

      escreva("Digite um numero inteiro: ")
      leia(x)

      enquanto x <> 0 faca

         se x % 2 <> 0 entao
           x <- x + 1
         fimse

         soma <- (5 * X) + 20
         escreval("Soma = ", soma)

         escreva("Digite um numero inteiro: ")
         leia(x)
         
        fimenquanto



Fimalgoritmo