Algoritmo "teste_enquanto"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

   x, soma : inteiro

Inicio

  escreva("Digite o primeiro numero: ")
  leia(x)

  soma <- 0
  enquanto x <> 0 faca
      soma <- soma + x
      escreva("Digite outro numero: ")
      leia(x)
  fimenquanto
  
  escreval("SOMA = ", soma)

Fimalgoritmo